version: '3.8'

services:
  ingestion:
    build: .
    container_name: capitolscope-ingestion
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Future services
  # web:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - ingestion
  #   restart: unless-stopped

  # email-service:
  #   build: ./email-service
  #   depends_on:
  #     - ingestion
  #   restart: unless-stopped

volumes:
  data:
  logs: 