"""Add Congress.gov API data fields to congress_members

Revision ID: 104b8ee08893
Revises: d61b8ca6ee5f
Create Date: 2025-07-10 14:10:39.042204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104b8ee08893'
down_revision = 'd61b8ca6ee5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('congress_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('congress_gov_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_attribution', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_api_update', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('congress_members', schema=None) as batch_op:
        batch_op.drop_column('last_api_update')
        batch_op.drop_column('image_attribution')
        batch_op.drop_column('image_url')
        batch_op.drop_column('congress_gov_url')

    # ### end Alembic commands ### 