"""changed securities fields to reference non uuid FKs

Revision ID: beaeff2be89f
Revises: 104b8ee08893
Create Date: 2025-07-10 22:47:17.153262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beaeff2be89f'
down_revision = '104b8ee08893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_sector_gics_code', sa.String(length=10), nullable=True))
        batch_op.alter_column('gics_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_sectors_gics_code'))
        batch_op.create_index(batch_op.f('ix_sectors_gics_code'), ['gics_code'], unique=True)
        batch_op.drop_constraint(batch_op.f('sectors_parent_sector_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sectors', ['parent_sector_gics_code'], ['gics_code'])
        batch_op.drop_column('parent_sector_id')

    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('sector_gics_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('exchange_code', sa.String(length=10), nullable=True))
        batch_op.drop_index(batch_op.f('ix_securities_asset_type_id'))
        batch_op.drop_index(batch_op.f('ix_securities_exchange_id'))
        batch_op.drop_index(batch_op.f('ix_securities_sector_id'))
        batch_op.drop_constraint(batch_op.f('unique_ticker_exchange'), type_='unique')
        batch_op.create_unique_constraint('unique_ticker_exchange', ['ticker', 'exchange_code'])
        batch_op.create_index(batch_op.f('ix_securities_asset_type_code'), ['asset_type_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_exchange_code'), ['exchange_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_sector_gics_code'), ['sector_gics_code'], unique=False)
        batch_op.drop_constraint(batch_op.f('securities_exchange_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('securities_sector_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('securities_asset_type_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'asset_types', ['asset_type_code'], ['code'])
        batch_op.create_foreign_key(None, 'sectors', ['sector_gics_code'], ['gics_code'])
        batch_op.create_foreign_key(None, 'exchanges', ['exchange_code'], ['code'])
        batch_op.drop_column('exchange_id')
        batch_op.drop_column('sector_id')
        batch_op.drop_column('asset_type_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sector_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exchange_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('securities_asset_type_id_fkey'), 'asset_types', ['asset_type_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('securities_sector_id_fkey'), 'sectors', ['sector_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('securities_exchange_id_fkey'), 'exchanges', ['exchange_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_securities_sector_gics_code'))
        batch_op.drop_index(batch_op.f('ix_securities_exchange_code'))
        batch_op.drop_index(batch_op.f('ix_securities_asset_type_code'))
        batch_op.drop_constraint('unique_ticker_exchange', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_ticker_exchange'), ['ticker', 'exchange_id'])
        batch_op.create_index(batch_op.f('ix_securities_sector_id'), ['sector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_exchange_id'), ['exchange_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_asset_type_id'), ['asset_type_id'], unique=False)
        batch_op.drop_column('exchange_code')
        batch_op.drop_column('sector_gics_code')
        batch_op.drop_column('asset_type_code')

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_sector_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sectors_parent_sector_id_fkey'), 'sectors', ['parent_sector_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_sectors_gics_code'))
        batch_op.create_index(batch_op.f('ix_sectors_gics_code'), ['gics_code'], unique=False)
        batch_op.alter_column('gics_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('parent_sector_gics_code')

    # ### end Alembic commands ### 