"""add_prefix_field_to_congress_members

Revision ID: c51ba2f145fb
Revises: 20250109_063000
Create Date: 2025-07-09 13:29:53.454068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c51ba2f145fb'
down_revision = '20250109_063000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('congress_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_congress_members_prefix'), ['prefix'], unique=False)

    with op.batch_alter_table('daily_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_date', sa.Date(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_daily_prices_date'))
        batch_op.drop_index(batch_op.f('idx_daily_price_date'))
        batch_op.create_index('idx_daily_price_date', ['price_date'], unique=False)
        batch_op.drop_index(batch_op.f('idx_daily_price_security_date'))
        batch_op.create_index('idx_daily_price_security_date', ['security_id', 'price_date'], unique=False)
        batch_op.drop_constraint(batch_op.f('unique_security_date'), type_='unique')
        batch_op.create_unique_constraint('unique_security_date', ['security_id', 'price_date'])
        batch_op.create_index(batch_op.f('ix_daily_prices_price_date'), ['price_date'], unique=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               server_default=sa.text("'USER'::userrole"),
               existing_nullable=False)

    with op.batch_alter_table('daily_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_daily_prices_price_date'))
        batch_op.drop_constraint('unique_security_date', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_security_date'), ['security_id', 'date'])
        batch_op.drop_index('idx_daily_price_security_date')
        batch_op.create_index(batch_op.f('idx_daily_price_security_date'), ['security_id', 'date'], unique=False)
        batch_op.drop_index('idx_daily_price_date')
        batch_op.create_index(batch_op.f('idx_daily_price_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_prices_date'), ['date'], unique=False)
        batch_op.drop_column('price_date')

    with op.batch_alter_table('congress_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_congress_members_prefix'))
        batch_op.drop_column('prefix')

    # ### end Alembic commands ### 