"""Make chamber and state nullable in congress_members

Revision ID: ead6b9a17f33
Revises: c51ba2f145fb
Create Date: 2025-07-09 22:57:30.873804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead6b9a17f33'
down_revision = 'c51ba2f145fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('congress_members', schema=None) as batch_op:
        batch_op.alter_column('chamber',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('congress_members', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('chamber',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ### 